<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2016-2017 Stephan Kreutzer

This file is part of edl_to_edl_fulfiller_1_jobfile_1 workflow, a submodule of the
digital_publishing_workflow_tools package.

edl_to_edl_fulfiller_1_jobfile_1 workflow is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

edl_to_edl_fulfiller_1_jobfile_1 workflow is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with edl_to_edl_fulfiller_1_jobfile_1 workflow. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="UTF-8"/>

  <xsl:template match="/edl-xml">
    <xsl:comment> This file was generated by edl_to_edl_fulfiller_1_jobfile.xsl of edl_to_edl_fulfiller_1_jobfile_1 workflow, a submodule of the digital_publishing_workflow_tools package, which is free software licensed under the GNU Affero General Public License 3 or any later version (see https://github.com/publishing-systems/digital_publishing_workflow_tools/ and http://www.publishing-systems.org). </xsl:comment><xsl:text>&#xA;</xsl:text>
    <edl-fulfiller-1-workflow-job>
      <xsl:if test="count(/edl-xml/span) &gt; 0 or count(/edl-xml/link) &gt; 0">
        <resources>
          <xsl:apply-templates select="/edl-xml/span"/>
          <xsl:apply-templates select="/edl-xml/link"/>
        </resources>
      </xsl:if>
    </edl-fulfiller-1-workflow-job>
  </xsl:template>

  <xsl:template match="/edl-xml/span">
    <resource identifier="{./@identifier}"/>
  </xsl:template>

  <xsl:template match="/edl-xml/link">
    <resource identifier="{./@identifier}"/>
  </xsl:template>

  <xsl:template match="node()|@*|text()"/>

</xsl:stylesheet>
